### ISSUE TITLE
robot_remocon crashes when pairing master not fully ready

### ISSUE THREAD

**Issue by bit-pirate** [rosjava/android_remocons#23]
There is some delay between the paring master (public) is available (robot_remocon finds it) and it being fully configured/ready. I currently believe this is the time interval when the pushing and pulling is going on.  If the robot_remocon connects during that time it crashes 100% of the time.

**Comment by stonier** [comment]
Ah, good point. I need a wait for service of some sort.

**Comment by stonier** [comment]
https://github.com/ros-java/android_apps/commit/7269f2798c350917bb4e8695078368f409acb18f

It wasn't checking to see if it had actually found the app manager namespace (via master system state lookups), and thus crashed when the namespace was still null.
