### ISSUE TITLE
robot_remocon: not showing robot & laptop battery status

### ISSUE THREAD

**Issue by bit-pirate** [rosjava/android_remocons#28]
That is also true for the apps launched by the remocon.
However, when starting the apps directly - and connecting to the private master - the battery statuses are shown.

Maybe this is due to unflipped topics for the battery statuses?

**Comment by stonier** [comment]
This data comes from diagnostics, so looks like it's not finding the /diagnostics (I think) topic correctly.

**Comment by bit-pirate** [comment]
Is the `/diagnostics` topic flipped by default by the gateway? If not we would always need to flip this topic for all turtlebot_apps, right?

**Comment by stonier** [comment]
Yes - I'd put it in the default flip list for the turtlebot app manager. Might need to check remocon to check where it's looking for the topic though (might be hardcoded to /diagnostics).

**Comment by stonier** [comment]
Needed diagnostics_aggs flipped.

https://github.com/robotics-in-concert/rocon_app_platform/commit/40de0606c598db03713a60536f2f8337d4bd229b
