### ISSUE TITLE
Nfc tag writer

### ISSUE THREAD

**Issue by stonier** [rosjava/android_remocons#3]
Take what we have in the graveyard and put it in https://github.com/ros-java/android_extras

**Comment by corot** [comment]
Put on android_extras, maybe. Also would be cool to write the Play Store URL for the remocon tool in the first record, and the connection parameters in the second.

**Comment by corot** [comment]
Implemented on this fork: https://github.com/robotics-in-concert/android_remocons/tree/hydro/rocon_nfc_writer
Pull request expected within the next 2 weeks
