### ISSUE TITLE
NFC should be in robot chooser?

### ISSUE THREAD

**Issue by stonier** [rosjava/android_remocons#34]
NFC could actually provide ESSID and rocon remocon information as well so you wouldn't even need to fire up the remocon to initiate it.

Does that mean it is redundant having it in the robot chooser?

**Comment by stonier** [comment]
Maybe not - you might not want to put the essid in the nfc tag if your robot is always moving among essid's. Stiill would be good to be able to trigger essid connection, automatic remocon start, role and app selection from the nfc tag in some use cases.

**Comment by corot** [comment]
All this is implemented on robotics-in-concert fork, that will be merged soon:
- Remocon can add new robots/concerts by reading the nfc tag, after pressing the NFC option on the add new master dialog
- Remocon can be automatically started by reading the same tag, going directly to the robot/concert specified in the tag. BUT the robot/concert don't get saved for further access; maybe this should be implemented.

**Comment by stonier** [comment]
Closing for now - it is kinda working. If we need to work on it further, we can open new issues.
