### ISSUE TITLE
Not finding platform_info

### ISSUE THREAD

**Issue by jihoonl** [rosjava/android_remocons#37]
sometimes when I pressed back button from app to return to remocon

it couldn't find platform_info service and shutdown

https://github.com/turtlebot/turtlebot/issues/106#issuecomment-27071429

**Comment by stonier** [comment]
At what step?

What was the result of not finding it - crash or message?

If message, what message?
If crash, stacktrace?

**Comment by stonier** [comment]
Reopen if it is reproduced with more information. Right now it's just noise.
